my_profile:
  target: dev
  outputs:
    dev:
      type: athena
      s3_staging_dir: 's3://salesdata7/athena-staging/'
      region_name: 'eu-north-1'
      schema: 'default'
      database: 'mydatabase'
      aws_profile: 'default'
